package com.nexus.access.backend.accessibility;
import java.time.OffsetDateTime; import java.util.UUID; import jakarta.persistence.*; import com.nexus.access.backend.user.User;
@Entity @Table(name="accessibility_profiles")
public class AccessibilityProfile {
	@Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id;
	@OneToOne(fetch=FetchType.LAZY) @JoinColumn(name="user_id", nullable=false, unique=true) private User user;
	@Column(name="mobility_reduced",nullable=false) private boolean mobilityReduced; @Column(nullable=false) private boolean wheelchair; @Column(name="visual_impairment",nullable=false) private boolean visualImpairment; @Column(name="hearing_impairment",nullable=false) private boolean hearingImpairment; @Column(name="cognitive_support",nullable=false) private boolean cognitiveSupport; @Column(name="high_contrast",nullable=false) private boolean highContrast; @Column(name="large_text",nullable=false) private boolean largeText; @Column(name="voice_navigation",nullable=false) private boolean voiceNavigation; @Column(name="simplified_mode",nullable=false) private boolean simplifiedMode;
	@Column(name="created_at",nullable=false,updatable=false) private OffsetDateTime createdAt; @Column(name="updated_at",nullable=false) private OffsetDateTime updatedAt;
	@PrePersist void created(){createdAt=OffsetDateTime.now();updatedAt=createdAt;} @PreUpdate void updated(){updatedAt=OffsetDateTime.now();}
	public UUID getId(){return id;} public User getUser(){return user;} public void setUser(User v){user=v;} public boolean isMobilityReduced(){return mobilityReduced;} public void setMobilityReduced(boolean v){mobilityReduced=v;} public boolean isWheelchair(){return wheelchair;} public void setWheelchair(boolean v){wheelchair=v;} public boolean isVisualImpairment(){return visualImpairment;} public void setVisualImpairment(boolean v){visualImpairment=v;} public boolean isHearingImpairment(){return hearingImpairment;} public void setHearingImpairment(boolean v){hearingImpairment=v;} public boolean isCognitiveSupport(){return cognitiveSupport;} public void setCognitiveSupport(boolean v){cognitiveSupport=v;} public boolean isHighContrast(){return highContrast;} public void setHighContrast(boolean v){highContrast=v;} public boolean isLargeText(){return largeText;} public void setLargeText(boolean v){largeText=v;} public boolean isVoiceNavigation(){return voiceNavigation;} public void setVoiceNavigation(boolean v){voiceNavigation=v;} public boolean isSimplifiedMode(){return simplifiedMode;} public void setSimplifiedMode(boolean v){simplifiedMode=v;} public OffsetDateTime getCreatedAt(){return createdAt;} public OffsetDateTime getUpdatedAt(){return updatedAt;}
}
